mysql> CREATE TABLE sistema_vivo.cliente (
    ->     id INT(11) PRIMARY KEY AUTO_INCREMENT,
    ->     nome_completo VARCHAR(255) NOT NULL,
    ->     email VARCHAR(100) DEFAULT NULL,
    ->     telefone VARCHAR(50) DEFAULT NULL,
    ->
    ->     data_inscricao DATE NOT NULL,
    ->     termino DATE DEFAULT NULL,
    ->     data_pagamento DATE DEFAULT NULL,
    ->     mes_pagamento VARCHAR(50) DEFAULT NULL,
    ->
    ->     numero_bilhete VARCHAR(50) DEFAULT NULL,
    ->
    ->     pacote VARCHAR(100) DEFAULT NULL, -- Ex: "4 Mbs"
    ->     edificio VARCHAR(50) DEFAULT NULL, -- Número do edifício
    ->     apartamento VARCHAR(50) DEFAULT NULL, -- Ex: "N-102"
    ->     valor_mensalidade DECIMAL(15,2) DEFAULT NULL,
    ->
    ->     onu VARCHAR(255) DEFAULT NULL, -- Referência ONU
    ->     pppoe VARCHAR(100) UNIQUE NULL, -- Login PPPoE
    ->
    ->     observacao TEXT DEFAULT NULL,
    ->     ultima_atualizacao DATETIME DEFAULT CURRENT_TIMESTAMP
    ->         ON UPDATE CURRENT_TIMESTAMP
    -> );